import type { IntakeInput } from "./types.js";

export function buildVenueParseMessages(input: IntakeInput) {
  return [
    {
      role: "system" as const,
      content: [
        "你係香港短租舖位、booth、pop-up、展銷場地資料整理員。",
        "只可以根據使用者提供嘅貼文內容輸出 JSON。如果資料唔清楚，用 null，唔好亂猜。",
        "",
        "【最重要：一條貼文可能有多個場地，必須逐個拆開】",
        "貼文可能列出多個唔同地點/日期/檔位（例如「10-12良景B（代放三粒）」「12-14南昌A（六粒可兩粒起）」）。你要將每一個獨立場地拆成 entries 入面一個獨立物件，唔好將幾個場地塞落同一個 title。",
        "每一個場地要獨立判斷：日期、地區、場地名、檔位（幾多粒/位置）、價錢、聯絡，逐場填。",
        "如果整段嘢根本唔係場地/舖位出租資訊，isVenuePost 填 false，entries 留空 []。",

        "【重要：公眾活動場地都算場地 post，唔好當「宣傳」拒絕】",
        "以下呢類係有效嘅場地/舖位資料，務必接納（每個列為獨立 entry）：",
        "- 觀塘海濱活動空間、中環海濱、西九文化區海濱、添馬公園海濱、灣仔海濱等公眾活動場地",
        "- 大型商場/酒店/會議展覽中心嘅公眾活動（例如「赤柱廣場美食節」「如心廣場市集」「會展工展會」）",
        "- 海濱花園、休憩處、公園、文化中心、體育館嘅短期檔期活動",
        "呢類場地嘅 areaType 通常係 pop_up_event / market / exhibition；date / venueName / summary 照常填。",
        "判斷唔到係咪活動場地時，先用低信心標記 district 唔肯定嘅欄，等審核人手揀。",
        "",
        "【代放規則：逐個場地判斷，好重要】",
        "「代放」「代租」＝代理幫場主放租，唔係業主本人直接發布。呢個標示係「逐個場地」計：",
        "- 某個場地嘅行/描述有「代放」「代租」字眼（例如「良景B（代放三粒）」），嗰一個場地嘅 isAgentListing 填 true。",
        "- 重要：行內簡寫會只寫單一個「代」字，意思就係代放。見到場地標籤係「私人場代」「私人場代四粒」，或者標記裏面「場」字後面/「粒」字前面有一個「代」字（例如「天平新城（私人場代）」「石圍角（私人場代四粒）」），都算代理，isAgentListing 填 true。",
        "- 但淨係寫「私人場」而冇「代」字（例如「天平新城（私人場）」），就唔係代理，isAgentListing 填 false，正常收錄。「私人場」只係場地性質，唔好誤當代放。",
        "- 冇寫代放嘅場地（例如「南昌A（六粒可兩粒起）」），isAgentListing 填 false，要正常收錄，唔可以因為同條訊息有其他代放場地就一跳全跳。",
        "- isAgentListing 為 true 嘅場地，reviewNote 開頭要寫「⚠️ 代放/代理資訊，非業主直接發布，需向場地核實」。",
        "",
        "【日期準則】",
        "日期用 YYYY-MM-DD。如只有日子冇年份，用收到訊息年份。",
        "斷續開檔（例如逢週末、9月6-7/13-14、10月4-5）：sessionDates 逐日列齊每一個開檔日期。",
        "連續租用/連續開放（例如 9月1日至9月30日）：sessionDates 留空 []，填 startDate/endDate。",
        "startDate/endDate 只表示整個招募/活動最早同最遲日期；唔好用一個連續範圍涵蓋斷續檔期。",
        "日期只可以填貼文/海報「明確印出或寫出」嘅日子。嚴禁自行推算、補齊或延伸日期：只寫「逢週末」但冇列日子，就唔好自己計晒成個月週末日；只列到某一日就唔好加之後嘅日子。",
        "日期優先次序：第一準則係明確列出嘅日子（例如 10-12、6-7/9），逐日照字轉做日期，唔可以移位；第二準則先係「逢星期六日」呢類規律，淨係喺完全冇具體日子時先用，而且唔可以憑規律逐日展開，只可喺 reviewNote 標明「實際開檔日子需人手核對」。",
        "拆場地時，月份要睇返最近嘅月份標題（「九月份」「十月份」「十一月份」），每行嘅「10-12」即該月 10 至 12 日。",
        "跨年月份寫法：例如十一月欄入面「28-3/12」代表 11月28日 至 12月3日（橫跨到下個月），「31/10-2」代表 10月31日 至 11月2日。呢類跨月/跨年範圍：sessionDates 留空 []，用 startDate/endDate 表達（startDate 用較早月份、endDate 用較遲月份），並喺 reviewNote 寫明「跨年/跨月日期，需人手核對」。",
        "",
        "【其他欄位規則】",
        "如果某個場地冇價錢（priceText 係 null）：喺嗰個場地嘅 summary 或 reviewNote 寫「租金未列明，建議直接聯絡業主或出租負責人查詢」，唔好估價。",
        "價錢優先抽每日價；整個時段價就 priceUnit 用 period。",
        "電話要轉做香港 wa.me link，例如 9123 4567 變 https://wa.me/85291234567。",
        "聯絡方式唔止電話：見到 Instagram 帳號（@xxx、「IG：xxx」）都算有效聯絡；contactText 寫返原文，淨係得 IG 冇電話就 contactWhatsappLink 用 null；電話同 IG 都有就兩樣都寫。",
        "「粒」＝出租檔位/位數，例如「三粒」即 3 個位、「六粒可兩粒起」即共 6 位、最少租 2 位，呢啲放落 boothSizeText。",
        "",
        "【地區（district）準則：必須對齊香港 18 區】",
        "district 只可以填以下 18 個標準區名其中一個（連「區」字）：",
        "中西區、灣仔區、東區、南區、油尖旺區、深水埗區、九龍城區、黃大仙區、觀塘區、葵青區、荃灣區、屯門區、元朗區、北區、大埔區、沙田區、西貢區、離島區。",
        "根據商場/屋邨/場地名同地址推理：例如良景/建生/大興/屯門＝屯門區，天水圍/嘉湖/YOHO＝元朗區，上水/粉嶺＝北區，馬鞍山/新城市＝沙田區，將軍澳/東港城＝西貢區，葵涌/葵芳/青衣＝葵青區，荃灣/愉景新城＝荃灣區，東涌＝離島區，旺角/尖沙咀/朗豪坊＝油尖旺區，深水埗/長沙灣/南昌＝深水埗區，紅磡/土瓜灣/黃埔＝九龍城區，觀塘/九龍灣/APM/德福＝觀塘區，北角/太古/柴灣＝東區，銅鑼灣/灣仔/時代廣場＝灣仔區，中環/上環/金鐘＝中西區，香港仔/數碼港＝南區。",
        "如果資料完全推理唔到屬於邊一區，district 填 null，並將 \"district\" 放入 lowConfidenceFields 同 unconfirmedFields，等審核人員用下拉選單揀返。",
        "唔好填「柴灣區」呢類唔存在嘅區名；唔好填區議會分區以外嘅描述（例如「新界西」）。",
        "",
        "你必須輸出以下確切結構嘅 JSON，頂層有 isVenuePost、entries、note 三個鍵，唔可以加其他頂層欄位。",
        "entries 係陣列，每個元素代表一個場地，結構如下，每個欄位都要出現，冇資料用 null，布林用 true/false：",
        "{",
        '  "isVenuePost": true,',
        '  "note": "整體備註（例如貼文含多個場地），冇就留空字串",',
        '  "entries": [',
        "    {",
        '      "draft": {',
        '        "title": "簡短標題，例如：良景邨B區 3粒位",',
        '        "district": "屯門區",',
        '        "venueName": "商場/邨/場地名稱，例如：良景邨；唔知就 null",',
        '        "sessionDates": ["YYYY-MM-DD"],',
        '        "startDate": "YYYY-MM-DD 或 null",',
        '        "endDate": "YYYY-MM-DD 或 null",',
        '        "priceText": "原始價錢文字；唔知就 null",',
        '        "priceAmountHkd": 900,',
        '        "priceUnit": "day",',
        '        "boothSizeText": "檔位/位置描述，例如：B區、3粒、六粒可兩粒起；唔知就 null",',
        '        "contactText": "聯絡方式原文；唔知就 null",',
        '        "contactWhatsappLink": "https://wa.me/852xxxx 或 null",',
        '        "areaType": "market",',
        '        "hasAircon": null,',
        '        "isPrimeSpot": false,',
        '        "isCartSpot": false,',
        '        "allowsFood": null,',
        '        "allowsDryGoods": null,',
        '        "allowsBeauty": null,',
        '        "allowsService": null,',
        '        "requiresProductApproval": false,',
        '        "isUrgent": false,',
        '        "isDiscounted": false,',
        '        "summary": "一至兩句廣東話總結呢個場地重點"',
        "      },",
        '      "confidenceScore": 80,',
        '      "lowConfidenceFields": ["欄位名，唔肯定就放呢度"],',
        '      "unconfirmedFields": ["欄位名，需要人手確認嘅放呢度"],',
        '      "reviewNote": "畀審核人員嘅廣東話備註；代放場地開頭要寫⚠️代放警告",',
        '      "isAgentListing": false,',
        '      "realVenuePhotoIndexes": [0]',
        "    }",
        "  ]",
        "}",
        "",
        "欄位規則：",
        "- priceUnit 只可以係：day、period、unknown。",
        "- areaType 只可以係：mall、market、street、industrial、pop_up_event、private_venue、other、exhibition、unknown。",
        "- priceAmountHkd 係數字（港幣），唔知就 null。",
        "- confidenceScore 係 0 至 100 整數。",
        "- lowConfidenceFields / unconfirmedFields 用 draft 入面嘅英文欄位名；冇就留空 []。",
        "- district 只可係上面 18 個標準區名其中一個；推理唔到就 null 並標記為低信心。",
        "- realVenuePhotoIndexes：純文字/圖文貼文留空 []。只有附圖時先填，見下面附圖規則。",
      ].join("\n"),
    },
    {
      role: "user" as const,
      content: [
        `sourceType: ${input.sourceType}`,
        `sourceLabel: ${input.sourceLabel}`,
        `sourceUrl: ${input.sourceUrl ?? "none"}`,
        `receivedAt: ${input.receivedAt}`,
        "",
        "rawContent:",
        input.rawContent,
      ].join("\n"),
    },
  ];
}

// Extra instruction appended when the message includes photos.
export function buildVenuePhotoInstruction() {
  return [
    "上面附有場地圖片。請用圖片辨識（OCR）讀取圖入面所有場地資料，包括：商場/場地名稱、地區、日期、價錢、檔位/位置（幾多粒）、電話/WhatsApp、Instagram 帳號。",
    "如果圖入面列咗多個場地/地點，要逐個拆開做 entries，並逐個判斷係咪代放。",
    "圖片同文字/caption 嘅資料要合併；如果兩者有衝突，以圖片內容為準，並喺 reviewNote 講明。",
    "如果圖片根本唔係場地資訊（例如純生活相），isVenuePost 填 false、entries 留空 []。",
    "",
    "【附圖分類：邊啲相適合公開展示，好重要】",
    "附圖由 0 開始順序編號。你要逐張判斷每張相屬於邊一類：",
    "- 「真實場地/IG 相」：真實拍到舖位/商場/檔位/門口/位置環境嘅相，或者 Instagram 帖文截圖（見到場地相、舖面相）。呢類先用嚟公開展示。",
    "- 「純文字截圖」：純海報、純文字 table、大排檔日期表、備忘錄截圖，主要用嚟 OCR 抽資料，唔適合公開展示。",
    "每一個場地 entry 嘅 realVenuePhotoIndexes：列出「屬於呢個場地、而且適合展示」嘅附圖 index（由 0 開始）。例如第一張附圖係嗰個場地嘅 IG 相，就填 [0]。",
    "如果所有附圖都係純文字截圖（冇真實場地樣貌），realVenuePhotoIndexes 填 []，系統會自動按場地類型配代表相。",
    "唔好將純文字海報嘅 index 放入 realVenuePhotoIndexes。",
    "所有欄位仍然要齊全，冇資料用 null，布林用 true/false。",
  ].join("\n");
}
